package valyaJmartPK;

/**
 * Enumeration class ProductCategory 
 *
 * Valya Sandria Akiela
 * 2006522650
 */
public enum ProductCategory
{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, 
    MOTHERCARE,COSMETICS, HEALTHCARE, FURNITURE, JEWELRY,
    TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE, 
    PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING
}
